### ISSUE TITLE
`jeo:assemble` doesn't stop when `org.objectweb.asm` error is found

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#427]
I'm getting this:

```
[INFO] --- jeo:0.2.18:assemble (default-cli) @ benchmark ---
[INFO] Writing .class files to after/classes-optimized
org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 3: Method owner: expected Lorg/eolang/benchmark/BA;, but found I
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:275)
	at org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1074)
	at org.eolang.jeo.representation.bytecode.BytecodeClass.bytecode(BytecodeClass.java:171)
	at org.eolang.jeo.representation.xmir.XmlBytecode.bytecode(XmlBytecode.java:97)
	at org.eolang.jeo.representation.EoRepresentation.toBytecode(EoRepresentation.java:103)
	at org.eolang.jeo.improvement.ImprovementBytecodeFootprint.recompile(ImprovementBytecodeFootprint.java:77)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.eolang.jeo.improvement.ImprovementBytecodeFootprint.apply(ImprovementBytecodeFootprint.java:64)
	at org.eolang.jeo.AssembleMojo.execute(AssembleMojo.java:87)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
Caused by: org.objectweb.asm.tree.analysis.AnalyzerException: Method owner: expected Lorg/eolang/benchmark/BA;, but found I
	at org.objectweb.asm.tree.analysis.BasicVerifier.naryOperation(BasicVerifier.java:389)
	at org.objectweb.asm.tree.analysis.BasicVerifier.naryOperation(BasicVerifier.java:44)
	at org.objectweb.asm.tree.analysis.Frame.executeInvokeInsn(Frame.java:682)
	at org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:609)
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:171)
	... 33 more
[INFO] App.xmir compiled into after/classes-optimized/org/eolang/benchmark/App.class (268b)
org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 4: Type java.lang.ClassNotFoundException: com.exam.BA not present
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:279)
	at org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1074)
	at org.eolang.jeo.representation.bytecode.BytecodeClass.bytecode(BytecodeClass.java:171)
	at org.eolang.jeo.representation.xmir.XmlBytecode.bytecode(XmlBytecode.java:97)
	at org.eolang.jeo.representation.EoRepresentation.toBytecode(EoRepresentation.java:103)
	at org.eolang.jeo.improvement.ImprovementBytecodeFootprint.recompile(ImprovementBytecodeFootprint.java:77)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.eolang.jeo.improvement.ImprovementBytecodeFootprint.apply(ImprovementBytecodeFootprint.java:64)
	at org.eolang.jeo.AssembleMojo.execute(AssembleMojo.java:87)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
Caused by: java.lang.TypeNotPresentException: Type java.lang.ClassNotFoundException: com.exam.BA not present
	at org.objectweb.asm.tree.analysis.SimpleVerifier.getClass(SimpleVerifier.java:378)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isAssignableFrom(SimpleVerifier.java:360)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isAssignableFrom(SimpleVerifier.java:348)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isSubTypeOf(SimpleVerifier.java:212)
	at org.objectweb.asm.tree.analysis.BasicVerifier.binaryOperation(BasicVerifier.java:300)
	at org.objectweb.asm.tree.analysis.BasicVerifier.binaryOperation(BasicVerifier.java:44)
	at org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:569)
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:171)
	... 33 more
Caused by: java.lang.ClassNotFoundException: com.exam.BA
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:496)
	at java.base/java.lang.Class.forName(Class.java:475)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.getClass(SimpleVerifier.java:376)
	... 40 more
org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 1: Type java.lang.ClassNotFoundException: com.exam.BA not present
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:279)
	at org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1074)
	at org.eolang.jeo.representation.bytecode.BytecodeClass.bytecode(BytecodeClass.java:171)
	at org.eolang.jeo.representation.xmir.XmlBytecode.bytecode(XmlBytecode.java:97)
	at org.eolang.jeo.representation.EoRepresentation.toBytecode(EoRepresentation.java:103)
	at org.eolang.jeo.improvement.ImprovementBytecodeFootprint.recompile(ImprovementBytecodeFootprint.java:77)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.eolang.jeo.improvement.ImprovementBytecodeFootprint.apply(ImprovementBytecodeFootprint.java:64)
	at org.eolang.jeo.AssembleMojo.execute(AssembleMojo.java:87)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
Caused by: java.lang.TypeNotPresentException: Type java.lang.ClassNotFoundException: com.exam.BA not present
	at org.objectweb.asm.tree.analysis.SimpleVerifier.getClass(SimpleVerifier.java:378)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isAssignableFrom(SimpleVerifier.java:360)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isAssignableFrom(SimpleVerifier.java:348)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isSubTypeOf(SimpleVerifier.java:212)
	at org.objectweb.asm.tree.analysis.BasicVerifier.unaryOperation(BasicVerifier.java:180)
	at org.objectweb.asm.tree.analysis.BasicVerifier.unaryOperation(BasicVerifier.java:44)
	at org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:603)
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:171)
	... 33 more
Caused by: java.lang.ClassNotFoundException: com.exam.BA
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:496)
	at java.base/java.lang.Class.forName(Class.java:475)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.getClass(SimpleVerifier.java:376)
	... 40 more
org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 1: Type java.lang.ClassNotFoundException: com.exam.BA not present
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:279)
	at org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1074)
	at org.eolang.jeo.representation.bytecode.BytecodeClass.bytecode(BytecodeClass.java:171)
	at org.eolang.jeo.representation.xmir.XmlBytecode.bytecode(XmlBytecode.[INFO] BA.xmir compiled into after/classes-optimized/org/eolang/benchmark/BA.class (287b)
java:97)
	at org.eolang.jeo.representation.EoRepresentation.toBytecode(EoRepresentation.java:103)
	at org.eolang.jeo.improvement.ImprovementBytecodeFootprint.recompile(ImprovementBytecodeFootprint.java:77)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.eolang.jeo.improvement.ImprovementBytecodeFootprint.apply(ImprovementBytecodeFootprint.java:64)
	at org.eolang.jeo.AssembleMojo.execute(AssembleMojo.java:87)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
Caused by: java.lang.TypeNotPresentException: Type java.lang.ClassNotFoundException: com.exam.BA not present
	at org.objectweb.asm.tree.analysis.SimpleVerifier.getClass(SimpleVerifier.java:378)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isAssignableFrom(SimpleVerifier.java:360)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isAssignableFrom(SimpleVerifier.java:348)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isSubTypeOf(SimpleVerifier.java:212)
	at org.objectweb.asm.tree.analysis.BasicVerifier.naryOperation(BasicVerifier.java:388)
	at org.objectweb.asm.tree.analysis.BasicVerifier.naryOperation(BasicVerifier.java:44)
	at org.objectweb.asm.tree.analysis.Frame.executeInvokeInsn(Frame.java:684)
	at org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:609)
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:171)
	... 33 more
Caused by: java.lang.ClassNotFoundException: com.exam.BA
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:496)
	at java.base/java.lang.Class.forName(Class.java:475)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.getClass(SimpleVerifier.java:376)
	... 41 more
org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 4: Type java.lang.ClassNotFoundException: org.eolang.benchmark.F not present
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:279)
	at org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1074)
	at org.eolang.jeo.representation.bytecode.BytecodeClass.bytecode(BytecodeClass.java:171)
	at org.eolang.jeo.representation.xmir.XmlBytecode.bytecode(XmlBytecode.java:97)
	at org.eolang.jeo.representation.EoRepresentation.toBytecode(EoRepresentation.java:103)
	at org.eolang.jeo.improvement.ImprovementBytecodeFootprint.recompile(ImprovementBytecodeFootprint.java:77)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.eolang.jeo.improvement.ImprovementBytecodeFootprint.apply(ImprovementBytecodeFootprint.java:64)
	at org.eolang.jeo.AssembleMojo.execute(AssembleMojo.java:87)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
Caused by: java.lang.TypeNotPresentException: Type java.lang.ClassNotFoundException: org.eolang.benchmark.F not present
	at org.objectweb.asm.tree.analysis.SimpleVerifier.getClass(SimpleVerifier.java:378)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isAssignableFrom(SimpleVerifier.java:360)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isAssignableFrom(SimpleVerifier.java:348)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isSubTypeOf(SimpleVerifier.java:212)
	at org.objectweb.asm.tree.analysis.BasicVerifier.binaryOperation(BasicVerifier.java:302)
	at org.objectweb.asm.tree.analysis.BasicVerifier.binaryOperation(BasicVerifier.java:44)
	at org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:569)
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:171)
	... 33 more
Caused by: java.lang.ClassNotFoundException: org.eolang.benchmark.F
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:496)
	at java.base/java.lang.Class.forName(Class.java:475)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.getClass(SimpleVerifier.java:376)
	... 40 more
[INFO] B.xmir compiled into after/classes-optimized/org/eolang/benchmark/B.class (315b)
org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 3: Expected I, but found Lorg/eolang/benchmark/A;
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:275)
	at org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1074)
	at org.eolang.jeo.representation.bytecode.BytecodeClass.bytecode(BytecodeClass.java:171)
	at org.eolang.jeo.representation.xmir.XmlBytecode.bytecode(XmlBytecode.java:97)
	at org.eolang.jeo.representation.EoRepresentation.toBytecode(EoRepresentation.java:103)
	at org.eolang.jeo.improvement.ImprovementBytecodeFootprint.recompile(ImprovementBytecodeFootprint.java:77)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.eolang.jeo.improvement.ImprovementBytecodeFootprint.apply(ImprovementBytecodeFootprint.java:64)
	at org.eolang.jeo.AssembleMojo.execute(AssembleMojo.java:87)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
Caused by: org.objectweb.asm.tree.analysis.AnalyzerException: Expected I, but found Lorg/eolang/benchmark/A;
	at org.objectweb.asm.tree.analysis.BasicVerifier.copyOperation(BasicVerifier.java:102)
	at org.objectweb.asm.tree.analysis.BasicVerifier.copyOperation(BasicVerifier.java:44)
	at org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:326)
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:171)
	... 33 more
[INFO] A.xmir compiled into after/classes-optimized/org/eolang/benchmark/A.class (250b)
[INFO] Main.xmir compiled into after/classes-optimized/org/eolang/benchmark/Main.class (557b)
[INFO] F.xmir compiled into after/classes-optimized/org/eolang/benchmark/F.class (94b)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

I believe, it should stop and raise an exception. Instead, the build is `SUCCESS`.

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#429](https://github.com/objectionary/jeo-maven-plugin/issues/429) is still not solved.

**Comment by volodya-lombrozo** [comment]
@yegor256 This should be fixed in `0.2.20` version

**Comment by volodya-lombrozo** [comment]
@yegor256 Did we solve this problem?

From [this](https://github.com/objectionary/jeo-maven-plugin/issues/432#issuecomment-1905782752):

> @volodya-lombrozo [updated](https://github.com/objectionary/benchmark/commit/8cfdb18319c30f3d6c63607317e8bb1cd9f19a5f), indeed it fails now, thanks

**Comment by yegor256** [comment]
@volodya-lombrozo yes thanks

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#458](https://github.com/objectionary/jeo-maven-plugin/issues/458) is still not solved; solved: [#429](https://github.com/objectionary/jeo-maven-plugin/issues/429).

**Comment by 0pdd** [comment]
@yegor256 all 2 puzzles are solved here: [#429](https://github.com/objectionary/jeo-maven-plugin/issues/429), [#458](https://github.com/objectionary/jeo-maven-plugin/issues/458).
